version: '3.7'
services:
  server:
    build: ../server
    container_name: server
    hostname: server
    ports:
      - '3000:3000'
    volumes:
      - ../server:/usr/src//server
      - /usr/src/service//node_modules
    working_dir: /usr/src//server
    command: 'npm start'

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
